server {
  listen   8080;
  listen   [::]:8080;

  root /usr/share/nginx/html;
  index index.html;

  location = /search-config.json {
    add_header Cache-Control "no-store" always;
  }

  location / {
    if ( $uri = '/index.html' ) {
      add_header Cache-Control no-store always;
    }
    try_files $uri $uri/index.html /index.html;
    expires off;
  }
}
