server {
  listen   8080;
  listen   [::]:8080;

  root /usr/share/nginx/html;
  index index.html;

  include /tmp/revisium-robots-tag.conf;

  location = /robots.txt {
    default_type text/plain;
    add_header Cache-Control "no-store" always;
    include /tmp/revisium-robots-tag.conf;
    alias /tmp/revisium-robots.txt;
  }

  location = /search-config.json {
    add_header Cache-Control "no-store" always;
    include /tmp/revisium-robots-tag.conf;
  }

  location / {
    include /tmp/revisium-robots-tag.conf;
    if ( $uri = '/index.html' ) {
      add_header Cache-Control no-store always;
    }
    try_files $uri $uri/index.html /index.html;
    expires off;
  }
}
